# EnergyTask - Production properties
cat > src/main/resources/application-prod.properties << 'EOF'
# DataBace
spring.datasource.url=jdbc:postgresql://localhost:5432/taskFlow
spring.datasource.username=postgres
spring.datasource.password=1212
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Login
logging.level.com.energytask.app;=INFO
logging.level.org.springframework.web=INFO

server.forward-headers-strategy=framework
EOF