# EnergyTask - Production properties
# DataBase
spring.datasource.url=jdbc:postgresql://localhost:5432/taskFlow
spring.datasource.username=postgres
spring.datasource.password=1212
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.energytask.app=INFO
logging.level.org.springframework.web=INFO

# Server
server.forward-headers-strategy=framework

# Settings for file uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB
file.upload-dir=uploads